### ISSUE TITLE
 multiple factor levels lets say 300 can be synthesized using synthpop?

### ISSUE THREAD

**Issue by NikhilaGanta** [bnowok/synthpop#6]
Can a variable of multiple factor levels lets say 300 can be synthesized using synthpop if so can you please let me know the RAM requirements

**Comment by bnowok** [comment]
Yes, you can synthesise factors with a large number of levels but with some constraints and you will probably need to customise your synthesis. A few points to consider are listed below.

1) Don not use factors with a large number of levels as explanatory variables - change `predictor.matrix` or if you have one such factor synthesise it at the very end (adjust `visit.sequence`);
2) Group values in some way and then synthesise the higher level and use `"nested"` method (bootstrap sampling within strata) for the more detailed variable;
3) Try `"ctree"` method instead of the default `"cart"`.
